# ==============================================================================
# Copyright© The University of Texas at Austin, 2025. All rights reserved.
# Author: Alex Diaz (j.a.diaz@utexas.edu)
# 
# About
# --------------
# Configuration file for training
# ==============================================================================

model:
  name: lmscnet
  num_classes: 14

data:
  data_dir: "/home/adiaz/Documents/ros_ws/data" # Root of SemanticKITTI-formatted dataset
  label_map: "/home/adiaz/Documents/thesis/repos/LMSCNet/LMSCNet_refactor/configs/label_map.yaml"
  volume_size_max: [2.8, 1.85, 4.5] # (W, H, D) m
  volume_size_min: [-2.8, -1.35, -1.1] # (W, H, D) m
  voxel_size: 0.05 # m
  class_frequencies: "/home/adiaz/Documents/thesis/repos/LMSCNet/LMSCNet_refactor/configs/class_freq.npy"
  transform: false

eval:
  save_dir: "/home/adiaz/Documents/thesis/repos/LMSCNet/LMSCNet_refactor/evals/"
  checkpoint: "/home/adiaz/Documents/thesis/repos/LMSCNet/LMSCNet_refactor/checkpoints_overfit_5/best_model.pt"

train:
  split_ratio: [0.8, 0.1, 0.1] # [train, validate, test]
  epochs: 800
  batch_size: 3
  learning_rate: 0.001
  log_every: 5
  checkpoint_dir: checkpoints/